### Get
GET http://localhost:3000/api/animals

### Post a new object
POST http://localhost:3000/api/animals
Content-Type: application/json

{
    "id": "1",
    "name": "Dove",
    "extinct": false,
    "taxonomy": "Columbiformes"
}

### Delete
DELETE http://localhost:3000/api/animals/deletionExample

### Update
PUT http://localhost:3000/api/animals/1
Content-Type: application/json

{
    "id": "1",
    "name": "White-billed crow",
    "extinct": false,
    "taxonomy": "Corvus woodfordi"
}

